name: corona domains

on:
  schedule:
    - cron: "0 21 * * *"
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Installing setup-tools
      run: sudo apt-get install python3-setuptools
    - name: Install requirements
      run: pip3 install -r requirements.txt
    - name: Run script
      env: # Or as an environment variable
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        git checkout -b corona-domains-branch
        python3 run_data.py 'corona'
        git add ./data/json_files/*/\*.
        git commit -m 'adding corona domain json'
        git checkout master
        git merge corona-domains-branch
        git push origin master