name: covid domains

on:
  schedule:
    - cron: "0 23 * * *"
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Installing setup-tools
      run: sudo apt-get install python3-setuptools
    - name: Install requirements
      run: pip3 install -r requirements.txt
    - name: Run script
      env: # Or as an environment variable
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: python3 run_data.py 'covid'