name: generate json_data

on:
  schedule:
    - cron: "0 21 * * *"
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Installing setup-tools
      run: sudo apt-get install python3-setuptools
    - name: Install requirements
      run: pip3 install -r requirements.txt
    - name: Run script
      env: # Or as an environment variable
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        git config credential.helper "store --file=.git/credentials"
        echo "https://${{ secrets.githubpat }}:@github.com" > .git/credentials
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout -b json-data-new-branch
        python3 run_data.py
        git add .
        git commit -m 'adding json-data data'
        git checkout master
        git merge json-data-new-branch
        git push origin master